name: Build Cross-Platform Executables

on:
  push:
    branches:
      - main
      - feature/speed
  pull_request:
    branches:
      - main
      - feature/speed

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            output_name: WordFrequencyAnalyzer.exe
          - os: macos-latest
            output_name: WordFrequencyAnalyzer_mac
          - os: ubuntu-latest
            output_name: WordFrequencyAnalyzer_linux

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-tk libxcb-xinerama0 libxcb-cursor0
        sudo apt-get install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name ${{ matrix.output_name }} \
          --noupx \
          --hidden-import=pandas._libs.tslibs.base \
          --hidden-import=pandas._libs.tslibs.timedeltas \
          --hidden-import=pandas._libs.tslibs.np_datetime \
          --hidden-import=pandas._libs.tslibs.nattype \
          --hidden-import=pandas._libs.tslibs.timestamps \
          --collect-submodules=seaborn \
          --clean \
          --strip \
          --noconfirm \
          gui.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: WordFrequencyAnalyzer-${{ matrix.os }}
        path: dist/${{ matrix.output_name }}*